# Generated by Django 5.0 on 2024-01-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymFreak', '0003_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ex_routines',
            name='price',
        ),
        migrations.AddField(
            model_name='ex_routines',
            name='step1_image',
            field=models.ImageField(default='', upload_to='Ex_Routines/step1'),
        ),
        migrations.AddField(
            model_name='ex_routines',
            name='step2_image',
            field=models.ImageField(default='', upload_to='Ex_Routines/step2'),
        ),
        migrations.AddField(
            model_name='ex_routines',
            name='step3_image',
            field=models.ImageField(default='', upload_to='Ex_Routines/step3'),
        ),
        migrations.AddField(
            model_name='ex_routines',
            name='step4_image',
            field=models.ImageField(default='', upload_to='Ex_Routines/step4'),
        ),
        migrations.AddField(
            model_name='ex_routines',
            name='step5_image',
            field=models.ImageField(default='', upload_to='Ex_Routines/step5'),
        ),
        migrations.AddField(
            model_name='ex_routines',
            name='step6_image',
            field=models.ImageField(default='', upload_to='Ex_Routines/step6'),
        ),
        migrations.AlterField(
            model_name='ex_routines',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
