# Generated by Django 5.0 on 2024-01-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymFreak', '0004_remove_ex_routines_price_ex_routines_step1_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_consumed', models.FloatField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
