# Generated by Django 5.0 on 2024-01-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymFreak', '0005_calorieentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaloriesBurned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('exercise_type', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField()),
            ],
        ),
    ]
