# Generated by Django 5.0 on 2024-01-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymFreak', '0006_caloriesburned'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='Ex_routines/loginPage')),
                ('login_video', models.FileField(upload_to='Ex_routines/loginPage')),
            ],
        ),
    ]
