# Generated by Django 5.0 on 2024-01-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymFreak', '0007_loginpagesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginpagesettings',
            name='background_image',
            field=models.ImageField(upload_to='loginPage/'),
        ),
        migrations.AlterField(
            model_name='loginpagesettings',
            name='login_video',
            field=models.FileField(upload_to='loginPage/'),
        ),
    ]
