# Generated by Django 5.0 on 2024-01-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GymFreak', '0009_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginpagesettings',
            name='login_video',
        ),
    ]
