# Generated by Django 5.0 on 2024-01-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymFreak', '0010_remove_loginpagesettings_login_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMIEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi_value', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CaloriesBurnedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_burned', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='CaloriesBurned',
        ),
    ]
